[workspace]

members = [
"blog",
"ch15-4",
"ch15-5",
"ch15-6",
"ch16-1-threads",
"ch16-2-messages",
"ch16-3-mutex",
"ch17-2",
"ch17-3",
"ch18-1",
"ch18-2",
"ch18-3",
"ch19-1",
"ch19-2",
"ch19-3",
"ch19-4",
"ch19-6",
"custom-smart-ptr",
"hello_macro",
"hello_macro_derive",
"smart-ptrs",
]
